MODEL:
  TYPE: effnet
  NUM_CLASSES: 2
EN:
  STEM_W: 48
  STRIDES: [1, 2, 2, 2, 1, 2, 1]
  DEPTHS: [2, 4, 4, 6, 6, 8, 2]
  WIDTHS: [24, 32, 56, 112, 160, 272, 448]
  EXP_RATIOS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1792
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: custom
  IM_SIZE: 64
  BATCH_SIZE: 128
TEST:
  DATASET: custom
  IM_SIZE: 64
  BATCH_SIZE: 104
NUM_GPUS: 4
OUT_DIR: .
