MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 2
  LOSS_FUN: bce_with_logits
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.05
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: abnormal
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 64
  EVAL_PERIOD: 1
TEST:
  DATASET: abnormal
  SPLIT: val
  BATCH_SIZE: 200
  IM_SIZE: 64
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
SOFTMAX: False
OUT_DIR: .
